# Generated by Django 5.1.7 on 2025-03-13 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_score', models.IntegerField(default=0)),
                ('set_in_order_score', models.IntegerField(default=0)),
                ('shine_score', models.IntegerField(default=0)),
                ('standardize_score', models.IntegerField(default=0)),
                ('sustain_score', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='administration.cell')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='administration.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
